Repository Meal-Tiger/Meal-Tiger-Frontend, pull requests merged in 2023-02, with the labels that each got.

#284 259 improve styling of profile dropdown menu
  react-frontend/src/navbar/Dropdown/Dropdown.module.css
  react-frontend/src/navbar/Usermenu/Usermenu.js
  react-frontend/src/navbar/Usermenu/Usermenu.module.css
Labels: enhancement

#299 Fixes #288
  react-frontend/src/fonts.css
Labels: bug

#298 Fixes #294
  react-frontend/src/recipe-full-view/recipe-description/RecipeDescription.js
Labels: bug

#302 fix #287 and remove unnecessary images
  react-frontend/public/index.html
  react-frontend/public/logo192.jpg
  react-frontend/public/logo192.png
  react-frontend/public/logo192.webp
  react-frontend/public/logo512.jpg
  react-frontend/public/logo512.png
  react-frontend/public/logo512.webp
  react-frontend/src/navbar/Navbar.js
  react-frontend/src/navbar/Usermenu/user.png
  react-frontend/src/navbar/logo.png
  react-frontend/src/recipe-overview/RecipeCard/essen.jpg
  react-frontend/src/recipe-overview/RecipeCard/user.png
Labels: bug

#301 Fixes #300
  react-frontend/src/__tests__/api.test,js.js
  react-frontend/src/modules/api.js
  react-frontend/src/navbar/Usermenu/Usermenu.js
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: enhancement

#303 fix bug
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: bug

#309 remove manifest.json as the frontend is not designed to be a pwa
  react-frontend/public/index.html
  react-frontend/public/manifest.json
Labels: bug

#310 297 fix unresponsive design on my recipes page
  react-frontend/public/platzhalter.jpg
  react-frontend/src/user-recipe/user-recipe-card/UserRecipeCard.js
  react-frontend/src/user-recipe/user-recipe-card/UserRecipeCard.module.css
Labels: bug

#311 Improve visuals of ratings
  react-frontend/src/recipe-full-view/rating-editor/RatingEditor.js
  react-frontend/src/recipe-full-view/rating-editor/RatingEditor.module.css
  react-frontend/src/recipe-full-view/rating-section/RatingSection.js
  react-frontend/src/recipe-full-view/rating-section/RatingSection.module.css
Labels: bug

#312 Fix #307
  react-frontend/src/recipe-full-view/recipe-description/RecipeDescription.module.css
Labels: bug

#313 Fix #296
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: bug

#318 Created tests for ProfileImageInput
  react-frontend/src/__tests__/ProfileImageInput.test.js
Labels: tests

#316 Created tests for Navbar
  react-frontend/src/__tests__/Navbar.test.js
Labels: tests

#314 Fix #289 imageslider bug
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.js
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.module.css
Labels: bug

#325 fixed bug
  react-frontend/src/recipe-full-view/rating-editor/RatingEditor.js
  react-frontend/src/recipe-full-view/rating-section/RatingSection.js
Labels: bug
