Repository Meal-Tiger/Meal-Tiger-Frontend, pull requests merged in 2023-01, with the labels that each got.

#46 Add base css from design-guideline
  react-frontend/src/index.css
Labels: enhancement

#49 Change CSS of RecipeOverview as outlined in design guidelines
  react-frontend/src/App.js
  react-frontend/src/RecipeOverview/RecipeCard/RecipeCard.js
  react-frontend/src/RecipeOverview/RecipeCard/RecipeCard.module.css
  react-frontend/src/RecipeOverview/RecipeOverview.js
  react-frontend/src/RecipeOverview/RecipeOverview.module.css
Labels: enhancement

#50 added css for button / input
  react-frontend/src/index.css
Labels: enhancement

#53 Change css-variables & fix imageSlider view
  react-frontend/src/index.css
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.js
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.module.css
  react-frontend/src/vars.css
Labels: invalid

#56 Add Fonts
  react-frontend/src/fonts.css
  react-frontend/src/fonts/PTSans-Regular.woff2
  react-frontend/src/fonts/Raleway-SemiBold.woff2
  react-frontend/src/index.css
Labels: enhancement

#69 Add ReactContext state to store data
  react-frontend/src/recipe-editor/IngredientsContainerEditable.js
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: enhancement

#88 86 fix api wrapper not sending search parameters & search not updating cards
  react-frontend/src/RecipeOverview/RecipeOverview.js
  react-frontend/src/modules/api.js
Labels: bug

#89 61 Load recipe name into the image slider
  react-frontend/src/App.js
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.js
  react-frontend/src/recipe-full-view/recipe-description/RecipeDescription.js
Labels: bug

#94 60 add button for next page in overview
  react-frontend/src/App.js
  react-frontend/src/RecipeOverview/RecipeOverview.js
  react-frontend/src/RecipeOverview/RecipeOverview.module.css
  react-frontend/src/navbar/Searchbar/Searchbar.js
Labels: enhancement

#98 59 add throbber spinning wheel when loading is shown
  react-frontend/src/RecipeOverview/RecipeOverview.js
  react-frontend/src/modules/throbber/throbber.js
  react-frontend/src/modules/throbber/throbber.module.css
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.js
  react-frontend/src/recipe-full-view/recipe-description/RecipeDescription.js
Labels: enhancement, component

#147 Created test for ImageSlider
  react-frontend/src/__tests__/ImageSlider.test.js
Labels: tests

#146 Created test for Dropdown
  react-frontend/src/__tests__/Dropdown.test.js
Labels: tests

#145 Created test for RecipeFullView
  react-frontend/src/__tests__/RecipeFullView.test.js
Labels: tests

#144 Created test for Usermenu
  react-frontend/src/__tests__/Usermenu.test.js
Labels: tests

#142 Created test for uploadedImages
  react-frontend/src/__tests__/uploadedImages.test.js
Labels: tests

#141 Created test for IngredientsContainer
  react-frontend/src/__tests__/IngredientsContainer.test.js
Labels: tests

#140 Created test for IngredientsContainerEditable
  react-frontend/src/__tests__/IngredientsContainerEditable.test.js
Labels: tests

#139 Created test for IngredientsItem
  react-frontend/src/__tests__/IngredientsItem.test.js
Labels: tests

#138 Created test for Modal
  react-frontend/src/__tests__/Modal.test.js
Labels: tests

#137 Created test for RecipeCard
  react-frontend/src/__tests__/RecipeCard.test.js
Labels: tests

#136 Created test for RecipeDescription
  react-frontend/src/__tests__/RecipeDescription.test.js
Labels: tests

#135 Created test for RecipeEditor
  react-frontend/src/__tests__/RecipeEditor.test.js
Labels: tests

#134 Created test for Searchbar
  react-frontend/src/__tests__/Searchbar.test.js
Labels: tests

#133 Created test for throbber
  react-frontend/src/__tests__/throbber.test.js
Labels: tests

#154 95 footer component
  react-frontend/src/App.js
  react-frontend/src/footer/DataPrivacy/DataPrivacy.js
  react-frontend/src/footer/Footer.js
  react-frontend/src/footer/Footer.module.css
  react-frontend/src/footer/SiteNotice/SiteNotice.js
  react-frontend/src/index.css
  react-frontend/src/vars.css
Labels: enhancement

#155 119 create an error boundary
  react-frontend/src/App.js
  react-frontend/src/footer/Footer.js
  react-frontend/src/modules/ErrorBoundary/ErrorBoundary.js
Labels: enhancement

#167 107 error handling recipe full view
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.js
  react-frontend/src/recipe-full-view/recipe-description/RecipeDescription.js
Labels: enhancement

#176 shows success Modal when Recipe is saved #97
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: enhancement

#186 set difficulty default to 1 instead of 0 #168
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: bug

#184 added css for active searchbar #169
  react-frontend/src/navbar/Searchbar/Searchbar.module.css
Labels: bug

#188 bug fix Time is not updated when recipe is sent for the first time #185
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: bug

#193 Add: Error handling
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: enhancement

#195 Add: Create rating functionality
  react-frontend/src/modules/api.js
  react-frontend/src/recipe-full-view/CommentEditor/RatingEditor.js
  react-frontend/src/recipe-full-view/CommentEditor/RatingEditor.module.css
  react-frontend/src/recipe-full-view/RecipeFullView.js
Labels: enhancement

#197 196 add styling for rating editor
  react-frontend/src/index.css
  react-frontend/src/recipe-full-view/CommentEditor/RatingEditor.js
  react-frontend/src/recipe-full-view/CommentEditor/RatingEditor.module.css
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.module.css
Labels: enhancement

#199 Updated tests
  react-frontend/src/__tests__/ImageSlider.test.js
  react-frontend/src/__tests__/IngredientsContainerEditable.test.js
  react-frontend/src/__tests__/RecipeCard.test.js
  react-frontend/src/__tests__/RecipeEditor.test.js
  react-frontend/src/__tests__/RecipeOverview.test.js
Labels: bug, tests

#202 Add: show images as in database
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.js
Labels: enhancement

#203 Add: show images in recipe-overview
  react-frontend/src/RecipeOverview/RecipeCard/RecipeCard.js
Labels: enhancement

#230 228 show profile image in navbar
  react-frontend/src/App.js
  react-frontend/src/__tests__/RecipeCard.test.js
  react-frontend/src/__tests__/RecipeFullView.test.js
  react-frontend/src/__tests__/RecipeOverview.test.js
  react-frontend/src/navbar/Usermenu/Usermenu.js
  react-frontend/src/navbar/Usermenu/Usermenu.module.css
  react-frontend/src/recipe-overview/RecipeCard/RecipeCard.js
  react-frontend/src/recipe-overview/RecipeCard/RecipeCard.module.css
  react-frontend/src/recipe-overview/RecipeCard/essen.jpg
  react-frontend/src/recipe-overview/RecipeCard/user.png
  react-frontend/src/recipe-overview/RecipeOverview.js
  react-frontend/src/recipe-overview/RecipeOverview.module.css
Labels: enhancement

#225 9 implement profile editing page in code
  react-frontend/src/App.js
  react-frontend/src/modules/api.js
  react-frontend/src/navbar/Usermenu/Usermenu.js
  react-frontend/src/profile/Profile.js
  react-frontend/src/profile/Profile.module.css
  react-frontend/src/profile/profile-image-input/ProfileImageInput.js
  react-frontend/src/profile/profile-image-input/ProfileImageInput.module.css
Labels: component

#236 227 error modal on no recipes found cannot be closed
  react-frontend/src/recipe-overview/RecipeOverview.js
  react-frontend/src/recipe-overview/RecipeOverview.module.css
Labels: bug

#239 223 recipeeditor negative time can be set
  react-frontend/src/recipe-editor/RecipeEditor.js
Labels: bug

#240 fix: minimum to 1
  react-frontend/src/recipe-full-view/rating-editor/RatingEditor.js
Labels: bug

#244 Created tests for api wrapper and updated dev-dependencies
  react-frontend/package-lock.json
  react-frontend/package.json
  react-frontend/src/__tests__/api.test,js.js
Labels: tests

#257 Add touch gestures to imageslider
  react-frontend/package-lock.json
  react-frontend/package.json
  react-frontend/src/recipe-full-view/RecipeFullView.js
  react-frontend/src/recipe-full-view/image-slider/ImageSlider.js
Labels: enhancement

#260 Throbber is now centered
  react-frontend/src/modules/throbber/throbber.module.css
Labels: bug

#269 Fix styling issues
  react-frontend/src/footer/SiteNotice/SiteNotice.js
  react-frontend/src/index.css
  react-frontend/src/modules/pagination/pagination.module.css
  react-frontend/src/navbar/Navbar.module.css
Labels: bug

#262 254 create user account if it doesnt exist now
  react-frontend/src/modules/api.js
  react-frontend/src/profile/Profile.js
Labels: enhancement

#275 fix ingredients overflow into description #274
  react-frontend/src/recipe-full-view/recipe-description/RecipeDescription.js
  react-frontend/src/recipe-full-view/recipe-description/RecipeDescription.module.css
Labels: bug

#276 recipeCard title css adjustments #273
  react-frontend/src/recipe-overview/RecipeCard/RecipeCard.js
  react-frontend/src/recipe-overview/RecipeCard/RecipeCard.module.css
Labels: bug

#278 show profile image in recipecard #258
  react-frontend/src/recipe-overview/RecipeCard/RecipeCard.js
  react-frontend/src/recipe-overview/RecipeCard/RecipeCard.module.css
Labels: enhancement

#277 time and difficulty cannot be edited fix #272
  react-frontend/src/__tests__/uploadedImages.test.js
  react-frontend/src/recipe-editor/RecipeEditor.module.css
  react-frontend/src/recipe-editor/uploadedImages.js
Labels: bug
